config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'artists#new'
  resources :artists
  post '/create_artists', to: 'artists#create'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  require 'nokogiri'
  require 'open-uri'
  require 'rubygems'
  require 'net/http'
  require 'google/apis/customsearch_v1'
  require 'twitter'

  def index
    @artists = Artist.all
    @artist = Artist.find(params[:id])
  end

  def show
    @artists = Artist.all
    @artist = Artist.find(params[:id])

    name = @artist.name.downcase.capitalize

    # Twitter API Connection for latest Tweets

    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
      config.access_token = ENV["TWITTER_ACCES_TOKEN"]
      config.access_token_secret = ENV["TWITTER_ACCES_TOKEN_SECRET"]
    end

    @tweet = client.user_timeline("#{name}", result_type: "recent").take(4)

    # Google API connection for artist images

      gsearch = Google::Apis::CustomsearchV1::CustomsearchService.new
      gsearch.key = ENV["GOOGLE_SEARCH_KEY"]
      cx = ENV["GOOGLE_CX"]

      @results = gsearch.list_cses(
        name,
        cx: cx,
        num: 4,
        img_size: 'xlarge',
        search_type: 'image'
      )

    # Wikipedia Biography scraper

    wikiurl = "https://en.wikipedia.org/wiki/#{name.to_s.tr(' ', '_')}"
    response = Net::HTTP.get_response(URI(wikiurl))

    case response
    when Net::HTTPSuccess
      data = Nokogiri::HTML(open(wikiurl))
      @wikiscrape = data.css('#mw-content-text')
      puts @wikiscrape
    when Net::HTTPRedirection
      @wikiscrape = ""
      puts ""
    end


    # MTV News and tourdates scraper

    mtvurl = "http://www.mtv.com/artists/#{name.downcase.parameterize.to_s}/"
    response = Net::HTTP.get_response(URI(mtvurl))

    case response
    when Net::HTTPSuccess
      data = Nokogiri::HTML(open(mtvurl))
      @mtvscrape = data.css(".tourdate-item").take(8)
      @mtvnews = data.css("#profile_latest_news")
    when Net::HTTPRedirection
      @mtvscrape = ""
      @mtvnews = ""
    end



  end

  def new
    @artists = Artist.all
    @artist = Artist.new
  end

  def create
    @artists = Artist.all
    @artist = Artist.new(params.require(:artist).permit(:name))

    if @artist.save
      redirect_to artist_path(@artist)
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to root_path
  end

end

app/views/artists/index.html.erb
<div class="nav-menu">
  <div class="fixed">
    <ul>
      <%= link_to root_path do %>
      <li class="gold">SEARCH</li>
      <li class="whitey">FAVORITE</li>
      <li class="gold">ARTIST</li>
      <% end %>
    </ul>
    <ul>
      <%= form_for @artist, url: create_artists_path, html: {method: "post"} do |f| %>
        <li><%= f.label :name, id: "search" %></li>
        <li><%= f.text_field :name %></li>
        <li><a class="button"><%= f.submit("Scrape") %></a></li>
      <% end %>
    </u>
    <ul>
      <% @artists.each do |artist| %>
        <li> <%= link_to artist.name, artist_path(@artist, :id => artist.id) %> &nbsp;&nbsp;
        <%= link_to "x", artist, method: :delete, data: { confirm: 'Are you sure?' }, id: "remove" %></li>
      <% end %>
    </u>
  </div>
</div>
<div class="parallax-page">
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("Stock-Concert-Photo.jpg") %>
      <% else %>
          <% @images.each do |a| %>
          <%= image_tag a.css('.artist-content img')[1].attr('src') %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="row container">
      <div class="biography">
        <h2> BIOGRAPHY </h2>
        <% if @wikiscrape.blank? %>
          <p> Couldn't find biography of <%= @artist.name %> </p>
        <% else %>
        <% @wikiscrape.each do |a| %>
          <p><%= a.css('p')[0].text unless a.css('p')[0].text.length < 100  %></p>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("tc_and_topcats.jpg") %>
      <% else %>
        <% @images.each do |a| %>
        <%= image_tag a.css('.artist-content img')[2].attr('src') %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="news">
      <h2>NEWS</h2>
          <% if @mtvnews.blank? %>
            <p> Couldn't find news of <%= @artist.name %> </p>
          <% else %>
            <% @mtvnews.each do |a| %>
            <p><%= raw a.css('.multiline')[0] %></p>
            <p><%= raw a.css('.multiline')[4] %></p>
            <p><%= raw a.css('.multiline')[8] %></p>
            <p><%= raw a.css('.multiline')[12] %></p>
            <p><%= raw a.css('.multiline')[16] %></p>
            <p><%= raw a.css('.multiline')[20] %></p>
            <p><%= raw a.css('.multiline')[24] %></p>
            <p><%= raw a.css('.multiline')[28] %></p>
            <p><%= raw a.css('.multiline')[32] %></p>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("open_mic_night222.jpg") %>
      <% else %>
          <% @images.each do |a| %>
          <%= image_tag a.css('.artist-content img')[4].attr('src') %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="tourdates">
      <h2>TOUR DATES</h2>
        <% if @mtvscrape.blank? %>
          <p> Couldn't find tour dates of <%= @artist.name %> </p>>
        <% else %>
          <% @mtvscrape.each do |a| %>
            <li><%= raw a.css('.content-inner') %></li>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("Music_Festival_wallpaper.jpg") %>
      <% else %>
        <% @images.each do |a| %>
        <%= image_tag a.css('.artist-content img')[5].attr('src') %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="twitterfeed">
        <h2>TWITTER FEED</h2>
        <% if @tweet.blank? %>
          <p> We couldn't find any tweets of <%= @artist.name %> </p>
          <% else %>
          <% @tweet.collect do |tweet| %>
            <p><%= "#{tweet.user.screen_name}: #{tweet.text}" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/new.html.erb
<div class="nav-menu">
  <div class="fixed">
    <ul>
      <%= link_to root_path do %>
      <li class="gold">SEARCH</li>
      <li class="whitey">FAVORITE</li>
      <li class="gold">ARTIST</li>
      <% end %>
    </ul>
    <ul>
      <%= form_for @artist, url: create_artists_path, html: {method: "post"} do |f| %>
        <li><%= f.label :name, id: "search" %></li>
        <li><%= f.text_field :name %></li>
        <li><a class="button"><%= f.submit("Scrape") %></a></li>
      <% end %>
    </u>
    <ul>
      <% @artists.each do |artist| %>
        <li> <%= link_to artist.name, artist_path(@artist, :id => artist.id) %> &nbsp;&nbsp;
        <%= link_to "x", artist, method: :delete, data: { confirm: 'Are you sure?' }, id: "remove" %></li>
      <% end %>
    </u>
  </div>
</div>
<div class="parallax-page">
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("Stock-Concert-Photo.jpg") %>
      <% else %>
          <% @images.each do |a| %>
          <%= image_tag a.css('.artist-content img')[1].attr('src') %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="row container">
      <div class="biography">
        <h2> BIOGRAPHY </h2>
        <% if @wikiscrape.blank? %>
          <p> Couldn't find biography of <%= @artist.name %> </p>
        <% else %>
        <% @wikiscrape.each do |a| %>
          <p><%= a.css('p')[0].text unless a.css('p')[0].text.length < 100  %></p>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("tc_and_topcats.jpg") %>
      <% else %>
        <% @images.each do |a| %>
        <%= image_tag a.css('.artist-content img')[2].attr('src') %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="news">
      <h2>NEWS</h2>
          <% if @mtvnews.blank? %>
            <p> Couldn't find news of <%= @artist.name %> </p>
          <% else %>
            <% @mtvnews.each do |a| %>
            <p><%= raw a.css('.multiline')[0] %></p>
            <p><%= raw a.css('.multiline')[4] %></p>
            <p><%= raw a.css('.multiline')[8] %></p>
            <p><%= raw a.css('.multiline')[12] %></p>
            <p><%= raw a.css('.multiline')[16] %></p>
            <p><%= raw a.css('.multiline')[20] %></p>
            <p><%= raw a.css('.multiline')[24] %></p>
            <p><%= raw a.css('.multiline')[28] %></p>
            <p><%= raw a.css('.multiline')[32] %></p>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("open_mic_night222.jpg") %>
      <% else %>
          <% @images.each do |a| %>
          <%= image_tag a.css('.artist-content img')[4].attr('src') %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <h2>TOUR DATES</h2>
        <% if @mtvscrape.blank? %>
          <p> Couldn't find tour dates of <%= @artist.name %> </p>
        <% else %>
          <% @mtvscrape.each do |a| %>
            <li><%= raw a.css('.content-inner') %></li>
          <% end %>
        <% end %>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @images.blank? %>
        <%= image_tag ("Music_Festival_wallpaper.jpg") %>
      <% else %>
        <% @images.each do |a| %>
        <%= image_tag a.css('.artist-content img')[5].attr('src') %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="twitterfeed">
        <h2>TWITTER FEED</h2>
        <% if @tweet.blank? %>
          <p> We couldn't find any tweets of <%= @artist.name %> </p>
          <% else %>
          <% @tweet.collect do |tweet| %>
            <p><%= "#{tweet.user.screen_name}: #{tweet.text}" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<div class="nav-menu">
  <div class="fixed">
    <ul>
      <%= link_to root_path do %>
      <li class="gold">SEARCH</li>
      <li class="whitey">FAVORITE</li>
      <li class="gold">ARTIST</li>
      <% end %>

    </ul>
    <ul>
      <%= form_for @artist, url: create_artists_path, html: {method: "post"} do |f| %>
        <li><%= f.label :name, id: "search" %></li>
        <li><%= f.text_field :name %></li>
        <li><a class="button"><%= f.submit("Scrape") %></a></li>
      <% end %>
    </u>
    <ul>
      <% @artists.each do |artist| %>
        <li> <%= link_to artist.name, artist_path(@artist, :id => artist.id) %> &nbsp;&nbsp;
        <%= link_to "x", artist, method: :delete, data: { confirm: 'Are you sure?' }, id: "remove" %></li>
      <% end %>
    </u>
  </div>
</div>
<div class="parallax-page">
  <div class="parallax-container">
    <div class="parallax">
      <% if @results.blank? %>
        <%= image_tag ("parallax2-1.jpg") %>
      <% else %>
        <%= image_tag @results.items[0].link %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="row container">
      <div class="biography">
        <h1> <%= @artist.name.upcase %> </h1>
        <h2> BIOGRAPHY </h2>
        <% if @wikiscrape.blank? %>
          <p> Couldn't find biography of <%= @artist.name %></p>
        <% else %>
        <% @wikiscrape.each do |a| %>
          <p><%= a.css('p')[0].text unless a.css('p')[0].text.length < 100  %></p>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @results.blank? %>
        <%= image_tag ("tc_and_topcats.jpg") %>
      <% else %>
          <%= image_tag @results.items[1].link %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="news">
      <h2>NEWS</h2>
          <% if @mtvnews.blank? %>
            <p> Couldn't find news of <%= @artist.name %> </p>
          <% else %>
            <% @mtvnews.each do |a| %>
            <p><%= raw a.css('.multiline')[0] %></p>
            <p><%= raw a.css('.multiline')[2] %></p>
            <p><%= raw a.css('.multiline')[4] %></p>
            <p><%= raw a.css('.multiline')[6] %></p>
            <p><%= raw a.css('.multiline')[8] %></p>
            <p><%= raw a.css('.multiline')[10] %></p>
            <p><%= raw a.css('.multiline')[12] %></p>
            <p><%= raw a.css('.multiline')[14] %></p>
            <p><%= raw a.css('.multiline')[16] %></p>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @results.blank? %>
        <%= image_tag ("open_mic_night222.jpg") %>
      <% else %>
        <%= image_tag @results.items[2].link %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <h2> TOUR DATES </h2>
      <div class="tourdates">
        <% if @mtvscrape.blank? %>
          <p> Couldn't find tour dates of <%= @artist.name %> </p>
        <% else %>
          <% @mtvscrape.each do |a| %>
            <li><%= raw a.css('.content-inner') %></li>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax">
      <% if @results.blank? %>
        <%= image_tag ("Music_Festival_wallpaper.jpg") %>
      <% else %>
        <%= image_tag @results.items[3].link %>
      <% end %>
    </div>
  </div>
  <div class="section black">
    <div class="row container">
      <div class="twitterfeed">
        <h2>TWITTER FEED</h2>
        <% if @tweet.blank? %>
          <p> We couldn't find any tweets of <%= @artist.name %> </p>
          <% else %>
          <% @tweet.collect do |tweet| %>
          <p><span style="font-weight:600"><%= "#{tweet.user.screen_name}:" %></span>
             <%= "#{tweet.text}" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Scraper</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,900italic,900,800italic,700italic,100,100italic,200,200italic,300,300italic,400italic,500,500italic,600,600italic,700,800' rel='stylesheet' type='text/css'></head>
  <body>

    <div class="wrapper">
      <%= yield %>
    </div>

  <script>
  window.sr = ScrollReveal({ reset: true });
  sr.reveal('.section', { duration: 1000, distance: '0px', origin: "top", scale: 1,
  });
  </script>
  </body>
</html>